### ISSUE TITLE
Concatenating poses in test.py

### ISSUE THREAD

**Issue by lichunshang** [ChiWeiHsiao/DeepVO_PyTorch#7]
https://github.com/ChiWeiHsiao/DeepVO-pytorch/blob/14d8790bd6c3426eeb19518668644d7d0e5bc529/test.py#L81-L104

For the section of the code here, what is the significance of checking for i == 0?

Specifically, at line 99 shown below, why only composing the last pose? Since all poses returned by the network are relative poses, shouldn't you compose all the relative poses returned by the network?

https://github.com/ChiWeiHsiao/DeepVO-pytorch/blob/14d8790bd6c3426eeb19518668644d7d0e5bc529/test.py#L99

**Comment by alexart13** [comment]
@lichunshang this is needed because of sequence overlap. With the default parameters you have sequence length = 6 and overlap = 1. So it looks like this:
Sequence 0 images: 1, 2, 3, 4, 5, 6
Sequence 1 images: 2, 3, 4, 5, 6 ,7
Sequence 2 images: 3, 4, 5, 6, 7, 8

The current implementation takes the whole Sequence 0 (i==0) and then just add the last pose from all the following sequences.

**Comment by lichunshang** [comment]
Ahh, I see. Overlap is set to set to sequence length minus one

https://github.com/ChiWeiHsiao/DeepVO-pytorch/blob/14d8790bd6c3426eeb19518668644d7d0e5bc529/test.py#L40

instead of just one in main.py. For sure an odd way to do this. 

https://github.com/ChiWeiHsiao/DeepVO-pytorch/blob/14d8790bd6c3426eeb19518668644d7d0e5bc529/main.py#L28

Thanks @alexart13
